### PR TITLE
fix(frontend): Fix story page

### LINKED ISSUE #428: [Bug]: Story page is broken
### Description

too lazy to write description

### Steps to reproduce

1.
2.
3.

### Demonstration(s) and additional context

_No response_

### PR DESCRIPTION
**Pull request by Norbiros**
Resolves #428

### CODE REVIEW

File: frontend/app/components/StoryViewer.vue [hunk 1]
```diff
@@ -1,5 +1,6 @@
 <script setup lang="ts">
-import { computed, ref } from 'vue'
+import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
+import AnimatedText from '~/components/AnimatedText.vue'
```
Comment (Kubaryt) [inline frontend/app/components/StoryViewer.vue:3]: ain't it autoimported? (all of those line)

**Review by Kubaryt — COMMENTED** [review]
just this and lgtm

File: frontend/app/components/AnimatedText.vue [hunk 2]
```diff
@@ -0,0 +1,43 @@
+<script setup lang="ts">
+import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
```
Comment (Kubaryt) [inline frontend/app/components/AnimatedText.vue:2]: delete this

**Review by Kubaryt — CHANGES_REQUESTED** [review]

**Review by Kubaryt — APPROVED** [review]
If tests pass lgtm
