### PR TITLE
fix: nickname censorship

### LINKED ISSUE #297: [Enhancement]: Ban Non-Polish chars from usernames
### My idea

Just an extract from the db:
```json
  {
    "username": "﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽",
    "email": ...,
    "created_at": "2025-02-24T19:56:37.066881",
    "password": ...,
    "id": ...,
    "is_leader": false,
    "team": null,
    "roles": "Default"
  },
```

### PR DESCRIPTION
**Pull request by goteusz-maszyk**
Resolves #297

### CODE REVIEW

**Comment by wikipop** [comment]
bloatware

File: backend/src/services/auth.rs [hunk 1]
```diff
@@ -222,4 +226,15 @@ impl AuthService {
...
+        // Basic Latin & numbers
+        c.is_ascii_alphanumeric() ||
+        // Latin-1 Supplement
+        ('\u{00C0}'..='\u{00FF}').contains(&c) ||
+        // Latin Extended-A
+        ('\u{0100}'..='\u{017F}').contains(&c) ||
+        // Latin Extended-B
+        ('\u{0180}'..='\u{024F}').contains(&c) ||
+        c.is_ascii_punctuation() || c == ' '
+    }
```
Comment (wikipop) [inline backend/src/services/auth.rs:239]: We allow space? Also design team would like to know whats max char number.

File: backend/src/services/auth.rs [hunk 2]
```diff
@@ -222,4 +226,15 @@ impl AuthService {
 
         Err(Error::UserNotFound)
     }
+    fn is_latin_extended(c: char) -> bool {
```
Comment (Kubaryt) [inline backend/src/services/auth.rs:229]: are you sure you cannot use validator crate for it? also even if you cant, I think request body validation should be handled by route not service

**Review by Kubaryt — CHANGES_REQUESTED** [review]

File: backend/src/services/auth.rs (hunk 1 above)
Comment (Kubaryt) [reply backend/src/services/auth.rs:239]: username is between 3 to 32 characters long, you can check macro attributes on RegisterModel struct for that
https://github.com/Hack4Krak/Hack4KrakSite/blob/master/backend/src/routes/auth/register.rs

File: backend/src/services/auth.rs [hunk 3]
```diff
@@ -222,4 +226,15 @@ impl AuthService {
...
+        // Basic Latin & numbers
+        c.is_ascii_alphanumeric() ||
+        // Latin-1 Supplement
+        ('\u{00C0}'..='\u{00FF}').contains(&c) ||
+        // Latin Extended-A
+        ('\u{0100}'..='\u{017F}').contains(&c) ||
+        // Latin Extended-B
+        ('\u{0180}'..='\u{024F}').contains(&c) ||
```
Comment (Norbiros) [inline backend/src/services/auth.rs:237]: Why we can't combine those 3 ranges to `'\u{00C0}'..='\u{024F}'`

File: backend/src/services/auth.rs (hunk 2 above)
Comment (Norbiros) [inline backend/src/services/auth.rs:229]: Add newline

File: backend/src/routes/auth/mod.rs [hunk 4]
```diff
@@ -44,7 +45,8 @@ impl error::ResponseError for AuthError {
             | AuthError::InvalidEmailAddress
             | AuthError::PasswordAuthNotAvailable
             | AuthError::InvalidConfirmationCode
-            | AuthError::ConfirmationCodeExpired => StatusCode::UNAUTHORIZED,
+            | AuthError::ConfirmationCodeExpired
+            | AuthError::InvalidUsername => StatusCode::UNAUTHORIZED,
```
Comment (Norbiros) [inline backend/src/routes/auth/mod.rs:49]: Invalid username is unauthorized?

**Review by Norbiros — CHANGES_REQUESTED** [review]

File: backend/src/services/auth.rs (hunk 2 above)
Comment (Norbiros) [inline backend/src/services/auth.rs:229]: Performance wise, it would be better to use matches!, it also could look better

**Review by Norbiros — CHANGES_REQUESTED** [review]

File: backend/src/services/auth.rs (hunk 3 above)
Comment (wojpo) [inline backend/src/services/auth.rs:237]: Combine those 3 ranges to `'\u{00C0}'..='\u{024F}'`

**Review by wojpo — CHANGES_REQUESTED** [review]

**Review by Norbiros — CHANGES_REQUESTED** [review]
Write tests

File: backend/src/services/auth.rs (hunk 2 above)
Comment (goteusz-maszyk) [reply backend/src/services/auth.rs:229]: then why do you validate email in service ????

Comment (Kubaryt) [reply backend/src/services/auth.rs]: where?

**Review by Kubaryt — CHANGES_REQUESTED** [review]
Validate it also on account::update and maybe admin::users::update

**Comment by goteusz-maszyk** [comment]
> Validate it also on account::update and maybe admin::users::update

admin can do anything but on update sure

**Comment by Kubaryt** [comment]
> > Validate it also on account::update and maybe admin::users::update
> 
> admin can do anything but on update sure

valid, admin can do anything

but for security reasons

```sql
UPDATE users
SET roles = 'default'
WHERE username = 'goteusz-maszyk'
```
/s

File: backend/src/models/user.rs [hunk 5]
```diff
@@ -262,3 +263,13 @@ impl UserRoles {
         }
     }
 }
+pub fn is_latin_extended(username: &str) -> Result<(), ValidationError> {
```
Comment (Kubaryt) [inline backend/src/models/user.rs:266]: im not sure if it should be here, but if you leave it here, then rename it to `validate_username`

**Review by Kubaryt — CHANGES_REQUESTED** [review]
besides that lgtm, but squash and name commit properly (fix(backend) prefix and also more describtive name)

**Comment by goteusz-maszyk** [comment]
> besides that lgtm, but squash and name commit properly (fix(backend) prefix and also more describtive name)

heard of squash & merge?

File: backend/tests/auth.rs [hunk 6]
```diff
@@ -98,6 +98,27 @@ async fn register_invalid_email() {
...
+    });
+
+    let request = test::TestRequest::post()
+        .uri("/auth/register")
+        .set_json(&register_payload)
+        .to_request();
+
+    let response = test::call_service(&app, request).await;
+    assert!(response.status().is_client_error());
+    // Verify if the body is proper JSON
```
Comment (Norbiros) [inline backend/tests/auth.rs:118]: There is no need to check if it is Json, either remove it or verify response body properly

File: backend/src/models/user.rs [hunk 7]
```diff
@@ -262,3 +263,13 @@ impl UserRoles {
         }
     }
 }
+pub fn validate_username_chars(username: &str) -> Result<(), ValidationError> {
+    if username.chars().all(|c| {
+        c.is_ascii_alphanumeric()
+            || ('\u{00C0}'..='\u{024F}').contains(&c)
```
Comment (Norbiros) [inline backend/src/models/user.rs:269]: Add comment describing those ranges

**Review by Norbiros — CHANGES_REQUESTED** [review]

**Comment by Kubaryt** [comment]
> > besides that lgtm, but squash and name commit properly (fix(backend) prefix and also more describtive name)
> 
> heard of squash & merge?

this is what I am talking about :3

**Review by Kubaryt — DISMISSED** [review]
just fix norbirosek things :3

File: backend/tests/auth.rs (hunk 6 above)
Comment (goteusz-maszyk) [reply backend/tests/auth.rs:118]: not my fault just copied above test you should have told it someone who made that
I DONT CARE

File: backend/src/routes/teams/management/rename.rs [hunk 8]
```diff
@@ -11,7 +12,10 @@ use validator::Validate;
 
 #[derive(Debug, Serialize, Deserialize, ToSchema, Validate)]
 pub struct ChangeNameModel {
-    #[validate(length(min = 3, max = 32))]
+    #[validate(
+        length(min = 3, max = 32),
+        custom(function = "validate_username_chars")
```
Comment (Norbiros) [inline backend/src/routes/teams/management/rename.rs:17]: Because we are using it in multiple names `validate_username_chars` isn't very good name

**Comment by Norbiros** [comment]
am

File: backend/tests/auth.rs (hunk 6 above)
Comment (Norbiros) [reply backend/tests/auth.rs:118]: So why you didn't copy everything? If I were you, I'd copy the entire
```rs
let container = GenericImage::new("mailhog/mailhog", "latest")
        .with_exposed_port(1025.tcp()) // SMTP port
        .with_exposed_port(8025.tcp()) // HTTP API port
        .with_wait_for(WaitFor::message_on_stdout("Creating API v2 with WebPath:"))
        .start()
        ```
        
 Because someone defined it in different test and you don't care :3

**Comment by goteusz-maszyk** [comment]
pm

**Review by Norbiros — APPROVED** [review]
