### PR TITLE
fix(frontend): fix login link bounding box in navbar

### LINKED ISSUE #794: [Bug]: Bounding box for link to login on navbar is too wide
### Description

Image

This is all link to /login. Same thing happens when you are logged in, just text is changed from Zaloguj się to Otwórz panel

### Steps to reproduce

1. Go to https://hack4krak.pl

### Demonstration(s) and additional context

_No response_

### PR DESCRIPTION
**Pull request by lajczi**
Fixes #794

### CODE REVIEW

File: frontend/app/components/Navbar.vue [hunk 1]
```diff
@@ -29,15 +29,13 @@ const navigationMenuProperties = computed(() => ({
...
-      <NuxtLink to="/login" class="text-md font-semibold flex justify-end w-full" :aria-label="isLoggedIn ? 'Otwórz panel' : 'Zaloguj się'">
+      <NuxtLink to="/login" class="text-md font-semibold flex grow-0" :aria-label="isLoggedIn ? 'Otwórz panel' : 'Zaloguj się'">
         <UIcon :name="isLoggedIn ? 'pixelarticons:user' : 'pixelarticons:login'" class="icon-md lg:hidden" />
 
         <span class="hidden lg:inline">
           {{ isLoggedIn ? "Otwórz panel" : "Zaloguj się" }}
         </span>
       </NuxtLink>
-
-      <div class="md:flex hidden flex-1 justify-end items-center" />
```
Comment (Sanielia) [inline frontend/app/components/Navbar.vue]: separate commit pls
