### PR TITLE
fix: hydration mismatch on static sites, minor fixes

### LINKED ISSUE #536: [Bug]: Hydration missmatch on /docs/... pages
### Description

Self explanatory 

### Steps to reproduce

1. Open /docs/rules
2. Hydration missmatch 
3. 😭 

### Demonstration(s) and additional context

Image

### PR DESCRIPTION
**Pull request by wikipop**
resolves #536

### CODE REVIEW

File: frontend/app/layouts/default.vue [hunk 1]
```diff
@@ -1,19 +1,5 @@
...
-// https://stackoverflow.com/questions/77135452/how-to-change-the-favicon-dynamically-in-nuxt-3
-function setFavicon() {
-  const isDark = usePreferredDark()
-  const favicon = computed(() => isDark.value ? '/favicon-dark.ico' : '/favicon-light.ico')
-
-  useFavicon(favicon, {
-    rel: 'icon',
-  })
-}
+import { setFavicon } from '~/utils/setFavicon'
```
Comment (Norbiros) [inline frontend/app/layouts/default.vue:2]: Maybe we can create useFavicon which has onMounted inside

File: frontend/app/layouts/static-page.vue [hunk 2]
```diff
@@ -1,3 +1,13 @@
+<script setup lang="ts">
+import { setFavicon } from '~/utils/setFavicon'
+
+useOgImage()
+
+onMounted(() => {
```
Comment (Norbiros) [inline frontend/app/layouts/static-page.vue:6]: I think it would be better to move it to the `app.vue` and copy it to `error.vue` so we'll have only 2 duplicates, not amount of layouts

File: frontend/app/pages/docs/[...slug].vue [hunk 3]
```diff
@@ -1,15 +1,16 @@
...
-if (!page.value) {
+definePageMeta({
+  layout: 'static-page',
+})
+
+if (!page.value?.title) {
   showError({
     statusCode: 404,
-    message: 'Strona nie została znaleziona',
+    message: 'Zdjecie nie zostalo znalezione',
```
Comment (Norbiros) [inline frontend/app/pages/docs/[...slug].vue:12]: Zdjęcie
```suggestion
    message: 'Strona nie została znalezione',
```

File: frontend/nuxt.config.ts [hunk 4]
```diff
@@ -11,13 +12,14 @@ const { commitHash, branchName } = getGitInfo()
 export default defineNuxtConfig({
   // Nuxt-specific configuration
 
+  // nuxt-seo must be configured before nuxt-content
```
Comment (Norbiros) [inline frontend/nuxt.config.ts:15]: We don't need that, revert it

File: frontend/nuxt.config.ts [hunk 5]
```diff
@@ -49,10 +51,17 @@ export default defineNuxtConfig({
 
   routeRules: {
     '/tasks/description/**': { swr: true },
-    '/faq': { prerender: true },
```
Comment (Norbiros) [inline frontend/nuxt.config.ts:52]: Add temporary redirect for /faq and /rules

**Review by Norbiros — CHANGES_REQUESTED** [review]

File: frontend/app/layouts/centered.vue [hunk 6]
```diff
@@ -1,4 +1,5 @@
 <script setup lang="ts">
+useOgImage()
```
Comment (Norbiros) [inline frontend/app/layouts/centered.vue:2]: It is already in app.vue you do not need that

File: frontend/app/utils/getDocsPages.ts [hunk 7]
```diff
@@ -0,0 +1,7 @@
+import { readdir } from 'node:fs/promises'
+import { join } from 'node:path'
+
+export async function getDocsPages() {
```
Comment (Norbiros) [inline frontend/app/utils/getDocsPages.ts:4]: Write short comment that it is a temporary solution

File: frontend/nuxt.config.ts [hunk 8]
```diff
@@ -1,3 +1,4 @@
+import { getDocsPages } from './app/utils/getDocsPages'
```
Comment (Norbiros) [inline frontend/nuxt.config.ts:1]: add it below comments

File: frontend/nuxt.config.ts [hunk 9]
```diff
@@ -15,9 +16,9 @@ export default defineNuxtConfig({
     '@nuxt/ui',
     '@nuxt/eslint',
     '@nuxt/image',
-    '@nuxt/content',
     '@nuxt/test-utils/module',
     '@nuxtjs/seo',
+    '@nuxt/content',
```
Comment (Norbiros) [inline frontend/nuxt.config.ts:21]: no need to change order here

**Review by Norbiros — CHANGES_REQUESTED** [review]
.

File: frontend/nuxt.config.ts (hunk 8 above)
Comment (wikipop) [reply frontend/nuxt.config.ts:1]: linter is setting this auto above

**Review by Norbiros — DISMISSED** [review]
just resolve conflicts

**Review by Kubaryt — APPROVED** [review]
