### PR TITLE
fix(backend): Use proper default env config for tests

### LINKED ISSUE #277: [Bug]: Default doesn't work properly for envs in load_test_config method
### Description

All envs except for jwt secret which is explicitly set in this config is just unit string ""

### Steps to reproduce

1. Open any test which loads test config
2. Print any env with declared default except for jwt secret
3. Make test panic so you see output

### Demonstration(s) and additional context

_No response_

### PR DESCRIPTION
**Pull request by Norbiros**
Resolves #277

### CODE REVIEW

**Review by goteusz-maszyk — CHANGES_REQUESTED** [review]
Replace all defaults with ..default::default()

**Comment by Norbiros** [comment]
It doesn't work like that mate

**Comment by goteusz-maszyk** [comment]
ok then fix conflicts

**Review by LupusVirtute — APPROVED** [review]
LGTM

File: backend/src/routes/teams/management/mod.rs [hunk 1]
```diff
@@ -8,7 +8,8 @@ pub mod rename;
 mod revoke_invitation;
 
 pub fn config(config: &mut utoipa_actix_web::service_config::ServiceConfig) {
-    config.service(change_leader::change_leader)
+    config
+        .service(change_leader::change_leader)
```
Comment (Kubaryt) [inline backend/src/routes/teams/management/mod.rs:12]: unrelated but ok ig

**Review by Kubaryt — APPROVED** [review]
LGTM
